var keyMirror = require('keymirror');

module.exports = keyMirror({
    ADMIN_PROPERTIES_STORE_DIALOG_MEASUREMENT: null,
    ADMIN_PROPERTIES_STORE_DIALOG_TYPE: null,
    ADMIN_PROPERTIES_STORE_DIALOG_NAME: null,
    ADMIN_PROPERTIES_SELECT_CATEGORY: null,

    ADMIN_PROPERTIES_CLEAR_DIALOG_DATA: null,
    ADMIN_PROPERTY_ADD_OR_UPDATE: null,

    ADMIN_PROPERTIES_ADD_DIALOG_OPEN: null,
    ADMIN_PROPERTIES_ADD_DIALOG_CLOSE: null,
    ADMIN_PROPERTIES_EDIT_DIALOG_OPEN: null,
    ADMIN_PROPERTIES_EDIT_DIALOG_CLOSE: null,

    ADMIN_PROPERTIES_ADD_NEW: null,
    ADMIN_PROPERTIES_DELETE_SELECTED: null,
    ADMIN_PROPERTIES_SELECT_FOR_DELETE: null
});