var keyMirror = require('keymirror');

module.exports = keyMirror({
    ADMIN_CATEGORIES_STORE_DIALOG_NAME: null,
    ADMIN_CATEGORIES_STORE_DIALOG_PROPERTY: null,
    ADMIN_CATEGORIES_CLEAR_DIALOG_DATA: null,
    ADMIN_CATEGORY_ADD_OR_UPDATE: null,
    ADMIN_CATEGORIES_ADD_DIALOG_OPEN: null,
    ADMIN_CATEGORIES_ADD_DIALOG_CLOSE: null,
    ADMIN_CATEGORIES_ADD_NEW: null,
    ADMIN_CATEGORIES_DELETE_SELECTED: null,
    ADMIN_CATEGORIES_DELETE_SELECTED_PROPERTY: null,
    ADMIN_CATEGORIES_SELECT_FOR_DELETE: null,
    ADMIN_CATEGORIES_EDIT_DIALOG_OPEN: null,
    ADMIN_CATEGORIES_EDIT_DIALOG_CLOSE: null,
    ADMIN_CATEGORIES_SELECT_CATEGORY: null
});