var keyMirror = require('keymirror');

module.exports = keyMirror({
    ADMIN_MEASURE_ADD_DIALOG_OPEN: null,
    ADMIN_MEASURE_ADD_DIALOG_CLOSE: null,
    ADMIN_MEASURE_EDIT_DIALOG_OPEN: null,
    ADMIN_MEASURE_EDIT_DIALOG_CLOSE: null,
    ADMIN_MEASURE_CLEAR_DIALOG_DATA: null,
    ADMIN_MEASURE_STORE_DIALOG_MEASUREMENT: null,

    ADMIN_MEASURE_STORE_DIALOG_NAME: null,
    ADMIN_MEASURE_STORE_DIALOG_MEASURE: null,
    ADMIN_MEASURE_STORE_DIALOG_TYPE: null,


    ADMIN_MEASURE_ADD_OR_UPDATE: null,
    ADMIN_MEASURE_DELETE_SELECTED: null,
    ADMIN_MEASURE_SELECT_FOR_DELETE: null
});