var keyMirror = require('keymirror');

module.exports = keyMirror({
    ADMIN_GOODS_ADD_DIALOG_OPEN: null,
    ADMIN_GOODS_ADD_DIALOG_CLOSE: null,
    ADMIN_GOODS_EDIT_DIALOG_OPEN: null,
    ADMIN_GOODS_EDIT_DIALOG_CLOSE: null,
    ADMIN_GOODS_CLEAR_DIALOG_DATA: null,

    ADMIN_GOODS_STORE_DIALOG_NAME: null,
    ADMIN_GOODS_STORE_DIALOG_PRICE: null,
    ADMIN_GOODS_STORE_DIALOG_QUANTITY: null,
    ADMIN_GOODS_STORE_DIALOG_MEASUREMENT: null,
    ADMIN_GOODS_STORE_DIALOG_DESCRIPTION: null,
    ADMIN_GOODS_STORE_DIALOG_CATEGORY: null,
    ADMIN_GOODS_STORE_DIALOG_PROPERTY: null,

    ADMIN_GOODS_ADD_OR_UPDATE: null,
    ADMIN_GOODS_DELETE_SELECTED: null,
    ADMIN_GOODS_SELECT_FOR_DELETE: null
});